executor: cluster-generic
cluster-generic-submit-cmd:
  sbatch
    --partition=batch
    --account=cedar
    --cpus-per-task={threads}
    --mem=4G
    --job-name=smk-{rule}-{wildcards}
    --output=test_logs/{rule}/{rule}-{wildcards}-%j.out
    --gres {resources.gres}
    --parsable
    --time={resources.time}
cluster-generic-status-cmd: python ./scripts/cluster-status.py
default-resources:
  - time="01:00:00"
  - gres="disk:1024"
jobs: 40
rerun-incomplete: True
use-conda: True

